package com.example.technicaltest

const val TAG_MOVIE_TITLE_LIST = "Movie.Title.List"
const val TAG_SEARCH_FIELD = "Movie.Search.Field"
const val TAG_SEARCH_BUTTON = "Movie.Search.Button"
const val TAG_LIST_HEADER = "Movie.Header.List"
const val TAG_LIST_ITEM = "Movie.List.Item"
const val TAG_ITEM_IMAGE = "Item.Image"
const val TAG_ITEM_TITLE = "Item.Title"
const val TAG_ITEM_RELEASE_DATE = "Item.Release.Date"
const val TAG_ITEM_VOTE_AVER = "Item.Vote.Average"
const val TAG_LOADING ="Loading.Indicator"
const val TAG_ITEM_MOVIE = "Item.Movie"
const val TAG_MOVIE_TITLE_DETAIL = "Movie.Title.Detail"
const val TAG_MOVIE_DETAIL_TITLE = "Movie.Detail.Title"
const val TAG_MOVIE_DETAIL_IMAGE = "Movie.Detail.Image"
const val TAG_MOVIE_DETAIL_DATE = "Movie.Detail.Date"
const val TAG_MOVIE_DETAIL_VOTE_AVERAGE = "Movie.Detail.VoteAverage"
const val TAG_MOVIE_DETAIL_STATUS = "Movie.Detail.Status"
const val TAG_MOVIE_DETAIL_BUDGET = "Movie.Detail.Budget"
const val TAG_MOVIE_DETAIL_VOTE = "Movie.Detail.Vote"
const val TAG_MOVIE_DETAIL_POPULARITY = "Movie.Detail.Popularity"
const val TAG_MOVIE_DETAIL_OVERVIEW = "Movie.Detail.Overview"
const val TAG_MOVIE_DETAIL_PRODUCTION_COUNTRY = "Movie.Detail.Production"